### ISSUE TITLE
No game startup

### ISSUE THREAD

**Issue by PavanLuca** [kz6fittycent/ohmygiraffe#1]
The game don't start at all.
![Informazioni](https://user-images.githubusercontent.com/123581658/219404332-a25f0b63-3d4c-4d13-8f51-ed460bacfd99.png)

**Comment by kz6fittycent** [comment]
I'm going to need more info. I am not having any issue running the snap on my machines. Can you please provide the output of this command?

`snap run ohmygiraffe`

**Comment by PavanLuca** [comment]
`ERROR: not connected to the gnome-3-34-1804 content interface.`

**Comment by kz6fittycent** [comment]
https://askubuntu.com/questions/1337374/error-not-connected-to-the-gnome-3-28-1804-content-interface 

Just replace the package name with yours (i.e. gnome-3-34-1804).

**Comment by PavanLuca** [comment]
![Schermata da 2023-02-16 18-12-13](https://user-images.githubusercontent.com/123581658/219438426-c2ade554-5e81-4679-bd67-e3e9697aa4e5.png)
Interesting, looks like the installation was broken or such, the game main folder contains only the folders **28**, **common** and **current** but EMPTY, do you think I have to reinstall the game?

**Comment by kz6fittycent** [comment]
You could try that but if you're not able to connect to that gnome interface, you'll have to ensure it's installed before you proceed.

**Comment by kz6fittycent** [comment]
actually it's normal that those folders are empty since the love binary for ohmygiraffe is in `/snap/ohmygiraffe` and not `~/snap/ohmygiraffe` 

![image](https://user-images.githubusercontent.com/14829816/219440353-8cc1e61a-6f00-45ec-9e42-002505d7658f.png)

**Comment by kz6fittycent** [comment]
As you can see, the `gnome-3-34-1804` snap is installed on my machine:

![image](https://user-images.githubusercontent.com/14829816/219442653-c90d7cc6-4712-4ccf-a74f-0c5350f31d19.png)

**Comment by kz6fittycent** [comment]
![image](https://user-images.githubusercontent.com/14829816/219446446-a4521e4d-caad-4a7a-8386-dce842ed971b.png)

**Comment by PavanLuca** [comment]
Alright, on my first screenshot I was on **Home**, not on **Computer** 🤦. Yeah, now this explains much about many games that weren't starting when I clicked them, where to install that interface? I hope there wouldn't be a side effect like system instability, general or random crashes and such. Actually I have gnome-3-28-1804 and gnome-3-38-2004, I thought that the version 3.38 was enough but looks like the game needs something specifically from 3.34, if I understood well stuff about dependencies reading posts on Zorin Forum.

**Comment by kz6fittycent** [comment]
The snap is contained so it wouldn't affect your system. It's just there to support various snaps that call up those other snaps as interfaces. Yes, it will take up more room, but will not affect your system. It'll just let this snap run as intended.

`gnome-3-38-2004` is for snaps that use `core20`. The `ohmygiraffe` snap using `core18`, so it can't use the `core20` based snaps.

`sudo snap install gnome-3-34-1804`

**Comment by PavanLuca** [comment]
Alright, I'll try again after applying that command, thanks. Maybe will also make other games work that previously didn't. And what's the reverse command? Now that I use Linux I'd like to have the reverse commands of any command I apply on the terminal, just in case I see suspicious behaviors 🐞🤔.

**Comment by kz6fittycent** [comment]
`sudo snap remove [snap name here]`

**Comment by PavanLuca** [comment]
Great, thanks.

**Comment by kz6fittycent** [comment]
you may need to run this as well:

`sudo snap connect ohmygiraffe:gnome-3-34-1804`

**Comment by PavanLuca** [comment]
Fantastic, game opened after I installed GNOME 3.34.1804 and I see no issue on the system or slowdowns so 👍. Really original game idea 🦒.
![Schermata da 2023-02-16 21-47-06](https://user-images.githubusercontent.com/123581658/219483313-4c52feae-066e-4bb8-af88-c8ec01252134.png)
I didn't even have to run `sudo snap connect ohmygiraffe:gnome-3-34-1804`, what would that do?

**Comment by kz6fittycent** [comment]
Awesome! Enjoy the game.
