### ISSUE TITLE
Impossible to customize window size

### ISSUE THREAD

**Issue by PavanLuca** [kz6fittycent/ohmygiraffe#2]
The window can be neither resized nor set to full-screen.

**Comment by kz6fittycent** [comment]
These are all "bugs" associated with the game - not the snap. I am not the developer of the game, I just packaged the snap for consumption.

**Comment by PavanLuca** [comment]
So the window size is impossible to resize by default? If so, is there a file that I have to edit to set it to full-screen by default? Probably I just have to set a value to `full-screen` or `1366×768` (my actual max resolution).

**Comment by kz6fittycent** [comment]
Again, this is not the fault of the snap but the application being snapped. Some games have a preset window size created by the original developer (not me) and the snap just respects those settings to allow the game/application to be played as the developer intended. You're welcome to reach out to the [original developer](http://www.ohmygiraffe.com/) to raise this issue.
