### ISSUE TITLE
Cursor control issue on first runs

### ISSUE THREAD

**Issue by PavanLuca** [kz6fittycent/ohmygiraffe#3]
When running for the first time in each play session when clicking on a point of the screen to make the giraffe run the game zoom out so the cursor control becomes relative, not direct. For instance, if I hold giraffe's head the game zooms out making me control the giraffe's head with the cursor NOT effectively on the head. I have to stop holding and reposition the cursor.

**Comment by kz6fittycent** [comment]
These are all "bugs" associated with the game - not the snap. I am not the developer of the game, I just packaged the snap for consumption.
