### ISSUE TITLE
Knocked out lions counter fail

### ISSUE THREAD

**Issue by PavanLuca** [kz6fittycent/ohmygiraffe#4]
When knocking out a lion AFTER the giraffe has been captured the counter misses it.
![Schermata da 2023-02-17 13-15-06](https://user-images.githubusercontent.com/123581658/219883919-d5ffe49a-ae6b-4364-a4ab-f9cf7710bea2.png)
As you can see above, a lion is knocked out on the left edge of the screen but the counter shows 0.

**Comment by kz6fittycent** [comment]
These are all "bugs" associated with the game - not the snap. I am not the developer of the game, I just packaged the snap for consumption.
