### ISSUE TITLE
Grapes eaten after being caught

### ISSUE THREAD

**Issue by PavanLuca** [kz6fittycent/ohmygiraffe#5]
Grapes can be eaten even after being caught. This makes the game to load the grapes' white spots but without connecting it to the previous.
![Schermata da 2023-02-17 13-19-07](https://user-images.githubusercontent.com/123581658/219884285-be0eb23e-09e7-4f72-b19d-027fa3f0e2af.png)

**Comment by kz6fittycent** [comment]
These are all "bugs" associated with the game - not the snap. I am not the developer of the game, I just packaged the snap for consumption.
