### ISSUE TITLE
Game quick launch

### ISSUE THREAD

**Issue by PavanLuca** [kz6fittycent/ohmygiraffe#6]
After installing the game it's neither added to **Games** section nor has the `Add to desktop` option, I could only add it to favorites (taskbar shortcut). I think this is something that you should add because most of the software that I install is added to its related category on main menu and allows adding its related shortcut to desktop.

Zorin OS Core, installations manager is Software (GNOME Software, gnome-software)

**Comment by kz6fittycent** [comment]
Please see the file here: 
https://github.com/kz6fittycent/ohmygiraffe/blob/master/snap/gui/ohmygiraffe.desktop 

If you know of another setting within that file, you're welcome to fork this repo and perform a PR for testing.

**Comment by PavanLuca** [comment]
Does that file exist on a game folder that I have? Because I can't find it by searching it with my file manager search feature. If it doesn't exist I'll download the shortcut and its icon from here.

**Comment by kz6fittycent** [comment]
`/snap/ohmygiraffe/current/meta/gui`

But you can't edit this file - it's `read-only`.

You'll need to fork this repo, and edit the file(s), then submit a pull-request (PR).

**Comment by PavanLuca** [comment]
I used my shortcuts properties that are already on my desktop as example for creating one for ohmygiraffe and I changed only `luca`'s **Access:** entry to `Read Only`.
![Schermata da 2023-02-20 18-49-22](https://user-images.githubusercontent.com/123581658/220173813-3dfc8166-27f8-4392-8768-7c857a4f2617.png)
And I could run the game but the icon hasn't been applied.
![Schermata da 2023-02-20 18-46-47](https://user-images.githubusercontent.com/123581658/220173836-880ed9bd-831b-4725-8486-fd5d1ad4d588.png)
Yet on **Desktop** directory there's some difference between my shortcut name and others that I created by their own options' menu.
![Schermata da 2023-02-20 18-47-38](https://user-images.githubusercontent.com/123581658/220173855-02acfc6a-2300-4ca6-96e5-497713ed3253.png)

**Comment by kz6fittycent** [comment]
Please re-read my previous requests - I would like to help you but this isn't constructive. I'm sorry, this isn't intended to be rude in any way. 

If you'll reference my other snap for Minecraft, you'll see there's very little difference between the two files: 
https://github.com/kz6fittycent/mc-installer/blob/master/snap/gui/mc-installer.desktop

However, to try to help, I've matched the settings between this snap and `mc-installer` to see if anything changes. If not, I'm going to close this issue since, as I've stated, these settings are within the binary from the upstream developer:


**REFERENCE:**
`/snap/ohmygiraffe/current/usr/bin/oh-my-giraffe.love`

```
function love.conf(t)
    --io.stdout:setvbuf("no")
    t.window.orientations = {
        portrait = false,
        portraitupsidedown = false,
        landscapeleft = true,
        landscaperight = true,
    }
    t.identity = "giraffe"
    t.version = "0.9.1"
    t.console = false 
    t.window.title = "oh my giraffe"
    t.window.icon = nil <- **HERE**
    t.window.width = 1024 <- **HERE**
    t.window.height = 640 <- **HERE**
    t.window.borderless = false <- **HERE**
    t.window.fullscreen = false <- **HERE**
    t.window.immersive = false <- **HERE**
    t.window.vsync = true
    t.window.fsaa = 0
    t.window.display = 1
    t.window.highdpi = true
    t.modules.audio = true
    t.modules.event = true
    t.modules.graphics = true
    t.modules.image = true
    t.modules.joystick = false
    t.modules.keyboard = true
    t.modules.math = true
    t.modules.mouse = true
    t.modules.physics = false
    t.modules.sound = true
    t.modules.system = true
    t.modules.timer = true
    t.modules.window = true
    t.modules.thread = true
end
```

If the window sizes are causing you frustration, please contact the original developer, as requested.

**Comment by kz6fittycent** [comment]
Please run the following command and test the latest build:
`sudo snap refresh ohmygiraffe --edge`

**Comment by PavanLuca** [comment]
Looks working as the latest/stable. Maybe I'll try forking as you said, thanks.

**Comment by kz6fittycent** [comment]
No I think you've misunderstood - you'll need to reach out to the original developer for `ohmygiraffe` to ask that the settings be applied to the binary - you're not gonna get anywhere with the snap or it's settings.
